name: supercart_pos
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^6.0.0
  http: ^1.5.0
  http_parser: ^4.1.2
  connectivity_plus: ^7.0.0

  # State management
  flutter_riverpod: ^2.6.1
  provider: ^6.1.5+1

  # UI & animation
  lucide_icons: ^0.257.0
  fl_chart: ^0.69.0
  cached_network_image: ^3.3.1
  animations: ^2.0.8
  skeletonizer: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg_kasir.png
    - .env
